"""empty message

Revision ID: bb405d58a8f8
Revises: edd1338eb554
Create Date: 2020-01-28 09:59:46.449426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb405d58a8f8'
down_revision = 'edd1338eb554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('users', 'isbn')
    op.drop_column('users', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
